name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      au_csv:
        description: 'AU CSV file name (default: au_link_check_results.csv)'
        required: false
        default: 'au_link_check_results.csv'
      nz_csv:
        description: 'NZ CSV file name (default: nz_link_check_results.csv)'
        required: false
        default: 'nz_link_check_results.csv'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrieve existing DB from gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1

      - name: Restore DB if exists
        run: |
          if [ -f gh-pages/broken_links.db ]; then
            cp gh-pages/broken_links.db ./broken_links.db
            echo "Restored existing broken_links.db"
          else
            echo "No existing DB found; starting fresh."
          fi

      - name: Check for required CSV files
        run: |
          if [ ! -f "${{ github.event.inputs.au_csv }}" ]; then
            echo "Error: AU CSV file '${{ github.event.inputs.au_csv }}' not found!"
            echo "Available files:"
            ls -la *.csv 2>/dev/null || echo "No CSV files found"
            exit 1
          fi
          if [ ! -f "${{ github.event.inputs.nz_csv }}" ]; then
            echo "Error: NZ CSV file '${{ github.event.inputs.nz_csv }}' not found!"
            echo "Available files:"
            ls -la *.csv 2>/dev/null || echo "No CSV files found"
            exit 1
          fi
          echo "Found required CSV files:"
          ls -la ${{ github.event.inputs.au_csv }} ${{ github.event.inputs.nz_csv }}

      - name: Generate Combined Report
        run: python report_generator.py --au-csv ${{ github.event.inputs.au_csv }} --nz-csv ${{ github.event.inputs.nz_csv }} --output-html combined_report.html

      - name: Prepare GitHub Pages deployment
        run: |
          mkdir -p gh-pages-deploy
          mv combined_report.html gh-pages-deploy/index.html
          cp broken_links.db gh-pages-deploy/ 2>/dev/null || echo "No broken_links.db to copy"
          cp *_link_check_results.csv gh-pages-deploy/ 2>/dev/null || echo "No CSV files to copy"

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-report
          path: |
            gh-pages-deploy/index.html
            gh-pages-deploy/broken_links.db

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-deploy
          publish_branch: gh-pages
          force_orphan: true